<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="FirstXMLFile.css"?>
<!DOCTYPE travel [
<!ELEMENT travel (country+)>
<!ELEMENT country (country-name, city+)>
<!ELEMENT country-name (#PCDATA)>
<!ELEMENT city (name, date, itinerary)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT itinerary (#PCDATA)>

<!ATTLIST country type (poland |germany |france) #REQUIRED>
]>

<travel>
<country type="poland">
    <country-name>Poland</country-name>
    <city>
        <name>Warsaw</name>
        <date>October 9-11</date>
        <itinerary>First stop, Warsaw, Poland. Poland is all about visiting Ann's extended family and taking in her heritage. Spending two and a half days expoloring some highlights including the Tomb of Unknown Soldier, Grand Opera, Parliament, Royal Lazienki Park, and Baroque Holy Cross Church, which houses an urn with the ashes of composer Frederick Chopin. The completely reconstructed Old Town boasts a number of historic monuments, art galleries, shops, charming restaurants, cafes, and craftsmen's workshops.</itinerary>
    </city>   
</country>

<country type="germany">
    <country-name>Germany</country-name>
    <city>
        <name>Berlin</name>
        <date>October 12-13</date>
        <itinerary>Entering Don's territory of Germany where he spent extended periods of time for work and speaks German, they hit Berlin first. They'll take a 4-hour tour of Berlin to get an overview of the city. Drive past the Bradenberg Gate, built as a triumphal arch for King Frederick Wilhelm II. The arch leads to the elegant Unter Den Linden Boulevard, which has seen much revitalization in recent years. Nearby, they will see Potsdam Square and the Museum Island. Other highlights in the former East Berlin include the Tiergarten Park, Bellevue Palace, the German Parliament building, and Checkpoint Charlie, the famous crossing point between East and West Berlin during the Cold War, which now houses a museum.</itinerary>
    </city>
    <city>
        <name>Dresden and Bamburg</name>
        <date>October 14</date>
        <itinerary>They'll make a stop in Dresden, the "Florence of the North." Enjoy their evening in Bamberg. One of the best undiscovered cities in this part of Germany, Bamberg was once the seat of the most powerful ruling family in the country. Having survived the ravages of war, Bamberg boasts a rich artistic heritage with a range of architectural styles represented. Perhaps they will begin exploring the lower city in the Maxplatz where they will find Neues Rathhaus and a daily market. Walking past the church of St. Martin, they can cross the Regnitz River and come to the imposing Domplatz. Behold one of the finest squares in Germany with its 11th-century cathedral, sculptures and museums. With the country's largest preserved Old Town, Bamberg has more than 2000 monuments and historical hallmarks, including the ancient Gardeners' Quarter and the old town hall. The town also has several museums and catacombs to explore.</itinerary>
    </city>
    <city>
        <name>Garmisch</name>
        <date>October 15</date>
        <itinerary>Situated at the foot of the Wetterstein mountain range is Garmisch-Partenkirchen, Germany's leading ski resort. The town of Garmisch-Partenkirchen is actually composed of two towns, Garmisch and Partenkirchen, which grew up on either side of the railway lines. Garmisch has a more cosmopolitan, modern atmosphere, while Partenkirchen retains more of its simple alpine village charm. Set in the heart of Partenkirchen and surrounded by two gardens, the moderate five-star Partenkirchner Hof was built in 1911. Designed in classic chalet style, the hotel consists of three interconnected buildings with bright flower boxes adorning the carved wood facade. The hotel features is a gourmet restaurant and informal cellar bar, serving Bavarian specialties. There are 61 guest rooms, which are decorated in a range of styles from modern to traditional. All rooms are large and feature satellite television, complimentary WiFi, in-room safe, minibar, and bathroom with hairdryer and robes. Guests may enjoy the indoor swimming pool, sauna, room service and bicycle rental. These two days are open for exploring the Bavarian Alps. There are two 'must see' options that we suggest for these two days: Zugspitze and Neuschwanstein.</itinerary>
    </city>
    <city>
        <name>Munich</name>
        <date>October 16</date>
        <itinerary>Day trip to experience Oktoberfest! Oktoberfest is the largest beer festival in the world and only Munich breweries are allowed to sell their beer in the tents. The tents accommodate between 2,000 and 10,000 people each; there are about 14 larger ones and some smaller ones. To give you some figures: in 2010 about 6.5 million people attending Oktoberfest, consuming about 5 million liters of beer, about 780,000 chickens, and about 75 oxen. Beside the beer tents, there is a large area with modern carnival rides as well as traditional ones like a flea circus. So there is much to eat and drink and to see!</itinerary>
    </city>
    <city>
        <name>Rothenburg</name>
        <date>October 19-20</date>
        <itinerary>They'll enjoy a free day in Rothenburg. One of the most charming cities in Germany, Rothenburg-ob-der- Tauber dates mainly to the 17th century. Surrounding the town is more than a mile of walls, with stairs every 200 - 300 yards, which you can climb for the view. The Rathaus or Town Hall is probably the best place to begin their explorations, as it is the heart of the town (Rathausplatz). Nearby is the Markplatz, which features the Herterlich Fountain, while the town's main churches are nearby. There are several museums, including the Imperial City Museum (housed in a former convent), the Medieval Criminal Museum (displaying instruments of torture.)</itinerary>
    </city>
    <city>
        <name>Ruedesheim</name>
        <date>October 21</date>
        <itinerary>One of the Rhine Valley's most popular towns, Ruedesheim is a quaint spot that is often filled with tourists. With half-timbered and gabled medieval houses, wine cellars, rustic restaurants, and a riverside promenade, the Ruedesheim summarily represents towns of the Reisling wine region. Highlights include the Weingass (Wine Alley) and Drosselgasse (Thrush Lane), which run through the heart of the Old Town. These narrow cobblestoned streets are lined with wine taverns and classic German restaurants. They can also visit Bromserburg Castle, which was built over 1,000 years ago and now houses a small wine museum. For excellent views of the river and countryside, you can take a chairlift up to the Niederwald Memorial - a massive statue set 1,000 feet above the town to celebrate the unification of the German Empire in 1871.</itinerary>
    </city>
    <city>
        <name>Rhine River Valley</name>
        <date>October 22</date>
        <itinerary>Ann and Don will enjoy a day out on the magnificent Rhine River with their one-day cruise pass. There are usually 2-3 departures in the morning and 2 in the afternoon so they go at their own pace, exploring enchanting little towns and sites along the way. Choose to leave early and take the cruise in both directions or depart later, returning to your originating town by taxi or train. The choice is theirs! On the cruise, they'll simply relax as they pass scenic countryside, many old fortresses and charming villages. A taped commentary offers explanations about the famous sights, such as the Loreley Rock, the fortresses of Rheinfels, Stolzenfels and Ehrenbreitstein and many more. Between Koblenz and Ruedesheim, stops include Boppard, St. Goarshausen, St. Goar, Oberwesel, and Bacharach amongst others; this is the most scenic portion of the river. </itinerary>
    </city>
</country>

<country type="france">
    <country-name>France</country-name>
    <city>
        <name>Paris</name>
        <date>October 23-24</date>
        <itinerary>The romantic city of Paris is divided into the Right and Left Bank by the Seine River. Relatively compact for a capital city, you can easily explore most key sites by foot. The Île de la Cité is the historic center and features Notre Dame Cathedral and the Conciergerie, while Sainte Chapelle is nearby. The Left Bank features the Eiffel Tower, Latin Quarter, Sorbonne University, Luxembourg Gardens, and Saint Germain des Pres with its Romanesque Church, boutiques, and cafes. Highlights of the Right Bank include the Concorde Square, Arc de Triomphe, Opera House, and Louvre. They'll troll along the impressive boulevards here for shopping, including the chic Champs Elysees with its designer shops and Boulevard Haussmann with its famous department stores. Above the city, charming Montmartre is home to the Moulin Rouge and Sacre-Coeur Basilica, while the Marais features 17th and 18th century town houses, trendy shops, and more. This evening, they'll head to the pier at the foot of the Eiffel Tower to embark the 2 1/2 hour Bateaux Parisiens Dinner and Illuminations Cruise on the Seine River. A "smart dress code" is required for the cruise (no jeans, running shoes, etc.). Begin boarding at 7:45 PM (cruise departs promptly at 8:30 PM) on this magical evening in the City of Lights, enjoying meticulously presented cuisine with attentive, discreet service. This voyage of discovery takes them through the majestic heart of Paris in a glass- covered boat. Dine on an all-inclusive menu, which features a choice of á-la-carte dishes: appetizer, starter, main dish, dessert, mineral waters, coffee and wines. Festive live music provides entertainment with the backdrop of one of the world's most romantic cities!</itinerary>
    </city>    
</country>
</travel>    